# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: YAPB, Yet Another Programming Blog
title_ja: またプログラマーのブログなの？
author: Malik Olivier Boussejra
author_ja: 木本 真理究
email: malik@boussejra.com
description: >
  Malik Oliver Boussejra's personal website. Write anything mostly about
  software engineering or language learning.
description_ja: >
  木本 真理究(まりく)の個人サイトです。ソフトウェア開発・言語学習などについていろいろ書いています。
  ご精読ありがとうございます。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://boussejra.com" # the base hostname & protocol for your site
twitter_username: malik_olivier
github_username:  malikolivier
google_analytics: UA-79560349-5
disqus:
    shortname: boussejra

# Build settings
markdown: kramdown
theme: minima

languages:
    en:
        name: English
        url: ''
        key: en
    ja:
        name: 日本語
        url: ja
        key: ja
