(function() {var implementors = {};
implementors["byteorder"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"byteorder/enum.BigEndian.html\" title=\"enum byteorder::BigEndian\">BigEndian</a>",synthetic:true,types:["byteorder::BigEndian"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"byteorder/enum.LittleEndian.html\" title=\"enum byteorder::LittleEndian\">LittleEndian</a>",synthetic:true,types:["byteorder::LittleEndian"]},];
implementors["fitrs"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"fitrs/struct.Fits.html\" title=\"struct fitrs::Fits\">Fits</a>",synthetic:true,types:["fitrs::fits::Fits"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"fitrs/struct.FitsDataArray.html\" title=\"struct fitrs::FitsDataArray\">FitsDataArray</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>,&nbsp;</span>",synthetic:true,types:["fitrs::fits::FitsDataArray"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"fitrs/struct.Hdu.html\" title=\"struct fitrs::Hdu\">Hdu</a>",synthetic:true,types:["fitrs::fits::Hdu"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"fitrs/struct.FitsIntoIter.html\" title=\"struct fitrs::FitsIntoIter\">FitsIntoIter</a>",synthetic:true,types:["fitrs::fits::FitsIntoIter"]},{text:"impl&lt;'f&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"fitrs/struct.FitsIter.html\" title=\"struct fitrs::FitsIter\">FitsIter</a>&lt;'f&gt;",synthetic:true,types:["fitrs::fits::FitsIter"]},{text:"impl&lt;'f&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"fitrs/struct.FitsIterMut.html\" title=\"struct fitrs::FitsIterMut\">FitsIterMut</a>&lt;'f&gt;",synthetic:true,types:["fitrs::fits::FitsIterMut"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"fitrs/enum.FitsData.html\" title=\"enum fitrs::FitsData\">FitsData</a>",synthetic:true,types:["fitrs::fits::FitsData"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"fitrs/enum.HeaderValue.html\" title=\"enum fitrs::HeaderValue\">HeaderValue</a>",synthetic:true,types:["fitrs::fits::HeaderValue"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
